server:
  port: 13002
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ruoyi.payment.api.entity
logging:
  level:
    com.ruoyi.payment.mapper: debug
spring:
  application:
    name: payment-server
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_advanced?useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://local.eureka10001.com:10001/eureka/,http://local.eureka10002.com:10002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  createUser: 596767880@qq.com
  gitee: https://github.com/heylaopao/springcloud