server:
  port: 19003
spring:
  application:
    name: order-hystrix
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://local.eureka10001.com:10001/eureka/,http://local.eureka10002.com:10002/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  createUser: please contact 596767880@qq.com
  describe: springboot admin monitor server






